import { ProcurementDoc, AiDocumentAnalysis, GoogleDocExportResult, GoogleTaskExportResult } from '../types';

/**
 * Creates a formatted Executive Briefing Document in Google Docs via the Google Docs REST API.
 */
export async function createGoogleDocBriefing(
  accessToken: string,
  doc: ProcurementDoc,
  analysis?: AiDocumentAnalysis | null
): Promise<GoogleDocExportResult> {
  const docTitle = `UK Procurement Briefing - ${doc.reference}: ${doc.title}`;

  // Step 1: Create Document
  const createRes = await fetch('https://docs.googleapis.com/v1/documents', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title: docTitle,
    }),
  });

  if (!createRes.ok) {
    const errText = await createRes.text();
    throw new Error(`Google Docs API error (${createRes.status}): ${errText}`);
  }

  const createdDoc = await createRes.json();
  const documentId = createdDoc.documentId;

  // Step 2: Assemble structured text content
  const nowStr = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const mandatoryList = analysis?.mandatoryRequirements?.length
    ? analysis.mandatoryRequirements.map((r, i) => `  ${i + 1}. ${r}`).join('\n')
    : doc.keyObligations.map((r, i) => `  ${i + 1}. ${r}`).join('\n');

  const authorityActionsList = analysis?.contractingAuthorityActions?.length
    ? analysis.contractingAuthorityActions.map((a, i) => `  [${a.priority} Priority] ${a.action} (Timeline: ${a.timeline})`).join('\n')
    : `  • ${doc.contractingAuthorityImpact}`;

  const supplierList = analysis?.supplierComplianceChecklist?.length
    ? analysis.supplierComplianceChecklist.map((s) => `  [ ] ${s}`).join('\n')
    : `  • ${doc.supplierImpact}`;

  const bestPracticesList = analysis?.recommendedBestPractices?.length
    ? analysis.recommendedBestPractices.map((b) => `  • ${b}`).join('\n')
    : '  • Maintain auditable procurement files\n  • Review supplier SQ submissions';

  const fullText = 
`UK PUBLIC PROCUREMENT REGISTRY — EXECUTIVE BRIEFING
=====================================================
Document Reference : ${doc.reference}
Official Title     : ${doc.title}
Category           : ${doc.categoryName} (${doc.documentType})
Publication Date   : ${doc.publicationDate}
Target Audience    : ${doc.targetAudience.join(', ')}
Applicable Law     : ${doc.applicableLegislation}
Threshold Scope    : ${doc.thresholdRelevance}
Briefing Date      : ${nowStr}
GOV.UK Source URL  : ${doc.govukUrl}
PDF Document URL   : ${doc.pdfUrl}
SHA-256 Checksum   : ${doc.sha256}

1. EXECUTIVE SUMMARY
-----------------------------------------------------
${analysis?.executiveSummary || doc.summary}

Commercial Impact:
${analysis?.commercialImpactSummary || doc.contractingAuthorityImpact}

Risk Rating: ${analysis?.riskRating || (doc.compliancePriority === 'High' ? 'HIGH' : 'MEDIUM')}
${analysis?.riskJustification || 'Ensure rigorous compliance to prevent procurement legal challenges and procedural cancellations.'}

2. KEY STATUTORY OBLIGATIONS & MANDATORY REQUIREMENTS
-----------------------------------------------------
${mandatoryList}

3. CONTRACTING AUTHORITY ACTION PLAN
-----------------------------------------------------
${authorityActionsList}

4. SUPPLIER COMPLIANCE & BIDDER CHECKLIST
-----------------------------------------------------
${supplierList}

5. RECOMMENDED COMMERCIAL BEST PRACTICES
-----------------------------------------------------
${bestPracticesList}

-----------------------------------------------------
Generated by UK Public Procurement Document Registry
GOV.UK Verified Scraper & Compliance Monitor
`;

  // Step 3: Insert text content via batchUpdate
  const updateRes = await fetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      requests: [
        {
          insertText: {
            location: {
              index: 1,
            },
            text: fullText,
          },
        },
      ],
    }),
  });

  if (!updateRes.ok) {
    console.warn('Batch update styling warning:', await updateRes.text());
  }

  return {
    docId: documentId,
    title: docTitle,
    docUrl: `https://docs.google.com/document/d/${documentId}/edit`,
    createdAt: new Date().toISOString(),
    docRef: doc.reference,
  };
}

/**
 * Creates an arbitrary formatted Document in Google Docs.
 */
export async function createGoogleDocCustom(
  accessToken: string,
  title: string,
  content: string
): Promise<{ documentId: string }> {
  const createRes = await fetch('https://docs.googleapis.com/v1/documents', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ title }),
  });

  if (!createRes.ok) {
    const errText = await createRes.text();
    throw new Error(`Google Docs API error (${createRes.status}): ${errText}`);
  }

  const createdDoc = await createRes.json();
  const documentId = createdDoc.documentId;

  const updateRes = await fetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      requests: [
        {
          insertText: {
            location: { index: 1 },
            text: content,
          },
        },
      ],
    }),
  });

  if (!updateRes.ok) {
    console.warn('Batch update styling warning:', await updateRes.text());
  }

  return { documentId };
}

/**
 * Generic task list creation in Google Tasks
 */
export async function createGoogleTasks(
  accessToken: string,
  listTitle: string,
  tasks: Array<{ title: string; notes?: string; dueDaysFromNow?: number }>
): Promise<Array<{ id: string; title: string }>> {
  const listsRes = await fetch('https://tasks.googleapis.com/tasks/v1/users/@me/lists', {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!listsRes.ok) {
    throw new Error(`Google Tasks API error (${listsRes.status})`);
  }

  const listsData = await listsRes.json();
  let targetList = listsData.items?.find((l: any) => l.title === listTitle);

  if (!targetList) {
    const createListRes = await fetch('https://tasks.googleapis.com/tasks/v1/users/@me/lists', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ title: listTitle }),
    });
    if (createListRes.ok) {
      targetList = await createListRes.json();
    } else {
      targetList = listsData.items?.[0];
    }
  }

  const listId = targetList?.id || '@default';
  const created: Array<{ id: string; title: string }> = [];

  for (const t of tasks) {
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + (t.dueDaysFromNow || 7));

    const taskRes = await fetch(`https://tasks.googleapis.com/tasks/v1/lists/${listId}/tasks`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title: t.title,
        notes: t.notes || '',
        due: dueDate.toISOString(),
      }),
    });

    if (taskRes.ok) {
      const data = await taskRes.json();
      created.push({ id: data.id, title: data.title });
    }
  }

  return created;
}


/**
 * Creates compliance action items in Google Tasks via Google Tasks REST API.
 */
export async function createGoogleTasksChecklist(
  accessToken: string,
  doc: ProcurementDoc,
  tasksList: Array<{ title: string; dueDays?: number; notes?: string }>
): Promise<GoogleTaskExportResult[]> {
  // Step 1: Find or create "UK Procurement Compliance" tasklist
  const listsRes = await fetch('https://tasks.googleapis.com/tasks/v1/users/@me/lists', {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!listsRes.ok) {
    throw new Error(`Google Tasks API error (${listsRes.status}): ${await listsRes.text()}`);
  }

  const listsData = await listsRes.json();
  let targetList = listsData.items?.find((l: any) => l.title === 'UK Procurement Compliance Actions');

  if (!targetList) {
    const createListRes = await fetch('https://tasks.googleapis.com/tasks/v1/users/@me/lists', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ title: 'UK Procurement Compliance Actions' }),
    });
    if (!createListRes.ok) {
      throw new Error(`Failed to create tasklist: ${await createListRes.text()}`);
    }
    targetList = await createListRes.json();
  }

  const listId = targetList.id;
  const createdResults: GoogleTaskExportResult[] = [];

  for (const item of tasksList) {
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + (item.dueDays || 14));
    const rfc3339Due = dueDate.toISOString();

    const notesText = `${item.notes || ''}\n\nRef: ${doc.reference} (${doc.title})\nSource: ${doc.govukUrl}\nPDF: ${doc.pdfUrl}`;

    const taskRes = await fetch(`https://tasks.googleapis.com/tasks/v1/lists/${listId}/tasks`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        title: item.title,
        notes: notesText,
        due: rfc3339Due,
      }),
    });

    if (taskRes.ok) {
      const taskData = await taskRes.json();
      createdResults.push({
        taskId: taskData.id,
        title: item.title,
        listTitle: targetList.title,
        due: rfc3339Due,
        createdAt: new Date().toISOString(),
        docRef: doc.reference,
      });
    }
  }

  return createdResults;
}

/**
 * Creates a complete, professional Bid Proposal Package Document in Google Docs.
 */
export async function createGoogleDocBidProposal(
  accessToken: string,
  pkg: any
): Promise<GoogleDocExportResult> {
  const docTitle = `Tender Bid Proposal - ${pkg.tenderTitle} (${pkg.companyProfile?.companyName || 'Bidder'})`;

  // Step 1: Create Document
  const createRes = await fetch('https://docs.googleapis.com/v1/documents', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title: docTitle,
    }),
  });

  if (!createRes.ok) {
    const errText = await createRes.text();
    throw new Error(`Google Docs API error (${createRes.status}): ${errText}`);
  }

  const createdDoc = await createRes.json();
  const documentId = createdDoc.documentId;

  // Step 2: Assemble structured text content
  const nowStr = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  let sectionsText = '';
  if (Array.isArray(pkg.sections)) {
    pkg.sections.forEach((sec: any) => {
      sectionsText += `\n\n=====================================================\n${sec.title.toUpperCase()}\nStatutory Basis: ${sec.statutoryAlignment}\n=====================================================\n\n${sec.content}\n`;
      if (sec.evaluatorRubricScoreEstimate?.tipToReachMaxScore) {
        sectionsText += `\n[EVALUATOR SCORING TIP: ${sec.evaluatorRubricScoreEstimate.tipToReachMaxScore}]\n`;
      }
    });
  }

  const fullText = 
`OFFICIAL UK PUBLIC SECTOR TENDER SUBMISSION DOSSIER
=====================================================
Tender Title          : ${pkg.tenderTitle}
Contracting Authority : ${pkg.contractingAuthority}
Tender Reference      : ${pkg.tenderReference || 'N/A'}
Submitting Bidder     : ${pkg.companyProfile?.companyName || 'Bidder Organization'}
Company Number        : ${pkg.companyProfile?.companyNumber || '[GAP: Insert Companies House Number]'}
Date of Submission    : ${nowStr}
Proposal Dossier ID   : ${pkg.id}
Estimated Win Score   : ${pkg.winStrategy?.overallWinProbabilityScore || 88}%
=====================================================

EXECUTIVE WIN STRATEGY & VALUE PROPOSITION
${pkg.winStrategy?.keyWinThemes?.map((w: any, i: number) => `\n${i + 1}. ${w.theme}\n   Value Proposition: ${w.valueProposition}\n   Proof Point: ${w.proofPoint}`).join('\n') || ''}

GAP & EVIDENCE AUDIT CHECKLIST (${pkg.totalIdentifiedGaps} Gaps Identified):
${pkg.sections?.flatMap((s: any) => s.identifiedGaps || []).map((g: any, i: number) => `  [ ] [${g.impactLevel}] ${g.description} -> Required Evidence: ${g.evidenceRequired}`).join('\n') || '  All evidence verified.'}

${sectionsText}

=====================================================
BidSmith ASF Statutory Compliance Intelligence
Procurement Act 2023 • PPN 06/20 • PPN 06/21 • PPN 02/23
`;

  // Step 3: Insert text
  const updateRes = await fetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      requests: [
        {
          insertText: {
            location: { index: 1 },
            text: fullText,
          },
        },
      ],
    }),
  });

  if (!updateRes.ok) {
    const errText = await updateRes.text();
    throw new Error(`Failed to populate Google Doc content: ${errText}`);
  }

  return {
    docId: documentId,
    title: docTitle,
    docUrl: `https://docs.google.com/document/d/${documentId}/edit`,
    createdAt: new Date().toISOString(),
    docRef: pkg.id,
  };
}

/**
 * Fetches current tasks from Google Tasks for verification and tracking.
 */
export async function fetchUserGoogleTasks(accessToken: string): Promise<any[]> {
  try {
    const listsRes = await fetch('https://tasks.googleapis.com/tasks/v1/users/@me/lists', {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    if (!listsRes.ok) return [];
    const listsData = await listsRes.json();
    const targetList = listsData.items?.find((l: any) => l.title === 'UK Procurement Compliance Actions') || listsData.items?.[0];
    if (!targetList) return [];

    const tasksRes = await fetch(`https://tasks.googleapis.com/tasks/v1/lists/${targetList.id}/tasks?showCompleted=true`, {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    if (!tasksRes.ok) return [];
    const tasksData = await tasksRes.json();
    return tasksData.items || [];
  } catch (err) {
    console.error('Error fetching Google Tasks:', err);
    return [];
  }
}
